import 'package:sucrose/src/xendit/enums/enums.dart';
import 'package:sucrose/src/xendit/models/entity/payment_method_props/xendit_virtual_account_props.dart';

class XenditVAPaymentMethod {
  /// Identifier provided by the merchant or automatically generated by Xendit if it was not provided.
  final String? referenceId;

  /// Describes whether or not the payment method can be reused for subsequent payments without going through the same linking process again.
  final XenditReusablePaymentMethod reusability;

  /// This contains the necessary information to describe a virtual account payment method. This will be null otherwise.
  final XenditVirtualAccountProps virtualAccount;

  /// Object that contains the required information to perform payments with virtual account
  XenditVAPaymentMethod({
    this.referenceId,
    required this.reusability,
    required this.virtualAccount,
  });

  factory XenditVAPaymentMethod.fromJson(Map<String, dynamic> json) =>
      XenditVAPaymentMethod(
        referenceId: json["reference_id"],
        reusability: json["reusability"],
        virtualAccount:
            XenditVirtualAccountProps.fromJson(json["virtual_account"]),
      );

  Map<String, dynamic> toJson() => {
        "reference_id": referenceId,
        "reusability": reusability.name,
        "type": "VIRTUAL_ACCOUNT",
        "virtual_account": virtualAccount.toJson(),
      };
}
