import 'package:sucrose/src/xendit/enums/enums.dart';
import 'package:sucrose/src/xendit/models/entity/payment_method_props/xendit_ewallet_props.dart';

class XenditEwalletPaymentMethod {
  /// Identifier provided by the merchant or automatically generated by Xendit if it was not provided.
  ///
  /// Maximum length: 255 characters
  final String? referenceId;

  /// Describes whether or not the payment method can be reused for subsequent payments without going through the same linking process again.
  final XenditReusablePaymentMethod reusability;

  /// This contains the necessary information to describe an ewallet payment method. This will be null otherwise.
  /// Please refer to Ewallet Object for more parameter details.
  final XenditEwalletProps ewallet;

  /// Object that contains the required information to perform payments with eWallet account
  XenditEwalletPaymentMethod({
    this.referenceId,
    required this.reusability,
    required this.ewallet,
  });

  factory XenditEwalletPaymentMethod.fromJson(Map<String, dynamic> json) =>
      XenditEwalletPaymentMethod(
        referenceId: json["reference_id"],
        reusability: json["reusability"],
        ewallet: XenditEwalletProps.fromJson(json["ewallet"]),
      );

  Map<String, dynamic> toJson() => {
        "reference_id": referenceId,
        "reusability": reusability.name,
        "type": "EWALLET",
        "ewallet": ewallet.toJson(),
      };
}
