name: sucrose
description: A Bridge Payment Gateway for Xendit and any other payment gateway.
version: 0.0.3
homepage: https://github.com/evnx32/sucrose
repository: https://github.com/evnx32/sucrose

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  dio: ^5.3.4
  flutter:
    sdk: flutter
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
